name: Terraform CI

on:
  pull_request:
    branches:
      - "*"

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Terraform init & validate
      runs-on: ubuntu-latest
      steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7

      - name: Initialize Terraform
        run: terraform init
      - name: Validate Terraform
        run: terraform validate

    - name: Security Scan
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Security Scan
        uses: atlassian/git-secrets-scan@0.5.1
